//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDCharacterManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDCharacterManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] favorite_star_selected {
            get {
                object obj = ResourceManager.GetObject("favorite_star_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] favorite_star_unselected {
            get {
                object obj = ResourceManager.GetObject("favorite_star_unselected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #Acid Splash
        ///Conjuration cantrip
        ///Casting Time: 1 action
        ///Range: 60 feet
        ///Components: V, S
        ///Duration: Instantaneous
        ///You hurl a bubble of acid. Choose one creature within
        ///range, or choose two creatures within range that are
        ///within 5 feet of each other. A target must succeed on a
        ///Dexterity saving throw or take 1d6 acid damage.
        ///This spell&apos;s damage increases by 1d6 when you reach
        ///5th level (2d6), 11th level (3d6), and 17th level (4d6).
        ///#Aid
        ///2nd-level abjuration
        ///Casting Time: 1 action
        ///Range: 30 feet
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string spelldescs {
            get {
                return ResourceManager.GetString("spelldescs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -0
        ///Acid Splash (sorcerer, wizard)
        ///Blade Ward (bard, sorcerer, warlock, wizard)
        ///Chill Touch (sorcerer, warlock, wizard)
        ///Dancing Lights (bard, sorcerer, wizard)
        ///Druidcraft (druid)
        ///Eldritch Blast (warlock)
        ///Fire Bolt (sorcerer, wizard)
        ///Friends (bard, sorcerer, warlock, wizard)
        ///Guidance (cleric, druid)
        ///Light (bard, cleric, sorcerer, wizard)
        ///Mage Hand (bard, sorcerer, warlock, wizard)
        ///Mending (bard, cleric, druid, sorcerer, wizard)
        ///Message (bard, sorcerer, wizard)
        ///Minor Illusion (bard, sorcerer, war [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string spelllist {
            get {
                return ResourceManager.GetString("spelllist", resourceCulture);
            }
        }
    }
}
